[package]
name = "pc_load"
version = "0.1.0"
edition = "2024"

[dependencies]
warp = "0.3"
tokio = { version = "1", features = ["full"] }
bytes = "1.1"
local-ip-address = "0.5"
serde = { version = "1.0", features = ["derive"] }
serde_derive = "1.0"
